version: '3.3'

services:
  composer:
    image: composer
    command: update
    volumes:
      - ./backend/wordpress:/app

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
    networks:
      - wpsite
  
  #Cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - wpsite

  wordpress:
    depends_on:
      - mysql
      - composer
      - redis
    image: wordpress:latest
    ports:
      - "8020:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./backend/wordpress:/var/www/html
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  mysql_data: {}